version: "3"


volumes:
  postgres_data_local:
  postgres_backup_local:


services:

  postgres:
    image: progressinator_postgres
    build:
      context: .
      dockerfile: ./config/postgres/Dockerfile
    env_file:
      - .env
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    ports:
      - "5432:5432"

  django:
    image: progressinator_django
    build:
      context: .
      dockerfile: ./config/django/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
